project:
  type: website
  output-dir: docs

website:
  title: "Yurkov Sergey"
  navbar:
    right:
      - text: CV
        url: https://registry.jsonresume.org/sergeyyurkov1?theme=macchiato
        target: _blank
      - software.qmd
      # - projects.qmd
      - text: Blog
        url: https://blog.csdn.net/sergeyyurkov1
        target: _blank
      - certificates.qmd
      # - notes.qmd
      # - text: Notes
      #   url: https://sergeyyurkov1.github.io/blog-notes/intro.html
      #   target: _blank

  # comments:
  #   utterances:
  #     repo: sergeyyurkov1/blog

format:
  html:
    theme: cosmo
    css: styles.css
